"""create transactions table

Revision ID: cd269f9540e9
Revises: 
Create Date: 2026-08-23 10:13:43.872108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd269f9540e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('transaction_id', sa.String(length=128), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('customer_id', sa.String(length=128), nullable=False),
    sa.Column('merchant_id', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('payment_method_id', sa.String(length=128), nullable=False),
    sa.Column('merchant_category', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index('ix_transactions_customer_id', 'transactions', ['customer_id'], unique=False)
    op.create_index('ix_transactions_device_id', 'transactions', ['device_id'], unique=False)
    op.create_index('ix_transactions_event_time', 'transactions', ['event_time'], unique=False)
    op.create_index('ix_transactions_merchant_id', 'transactions', ['merchant_id'], unique=False)
    op.create_index('ix_transactions_payment_method_id', 'transactions', ['payment_method_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_payment_method_id', table_name='transactions')
    op.drop_index('ix_transactions_merchant_id', table_name='transactions')
    op.drop_index('ix_transactions_event_time', table_name='transactions')
    op.drop_index('ix_transactions_device_id', table_name='transactions')
    op.drop_index('ix_transactions_customer_id', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
